import {
  getDeploymentBaseUrl,
  getDeploymentOverrides,
  getDeploymentString,
  resetDeploymentOverridesCache,
} from './deployment-overrides';

describe('deployment overrides', () => {
  let fetchSpy: jasmine.Spy;

  const respondWith = (body: unknown): void => {
    fetchSpy.and.returnValue(
      Promise.resolve({ ok: true, json: () => Promise.resolve(body) }),
    );
  };

  beforeEach(() => {
    resetDeploymentOverridesCache();
    fetchSpy = spyOn(window, 'fetch');
  });

  afterEach(() => {
    resetDeploymentOverridesCache();
  });

  it('reads a key written by the entrypoint', async () => {
    respondWith({ plainspaceHost: 'https://plainspace.apps.swecha.org' });

    expect(await getDeploymentString('plainspaceHost')).toBe(
      'https://plainspace.apps.swecha.org',
    );
    expect(fetchSpy).toHaveBeenCalledWith('assets/sync-config-default-override.json');
  });

  it('serves any key, not one hardcoded setting', async () => {
    // The point of the generic reader: a new deployment setting is a key here,
    // not a new module with its own fetch and cache.
    respondWith({
      plainspaceHost: 'https://ps.example.com',
      webDav: { baseUrl: 'https://cloud.example.com' },
      someFutureSetting: 'value',
    });

    expect(await getDeploymentString('someFutureSetting')).toBe('value');
    expect((await getDeploymentOverrides()).webDav).toEqual({
      baseUrl: 'https://cloud.example.com',
    });
  });

  it('trims surrounding whitespace', async () => {
    respondWith({ someKey: '  spaced  ' });

    expect(await getDeploymentString('someKey')).toBe('spaced');
  });

  it('resolves undefined for an absent key', async () => {
    respondWith({ otherKey: 'x' });

    expect(await getDeploymentString('someKey')).toBeUndefined();
  });

  it('resolves undefined for an empty, blank, or non-string value', async () => {
    // A malformed env var reaching the client must fall back, not be handed to a
    // consumer as a host or URL.
    for (const key of ['', '   ', 42, null, {}, []]) {
      resetDeploymentOverridesCache();
      respondWith({ someKey: key });
      expect(await getDeploymentString('someKey')).toBeUndefined();
    }
  });

  it('strips trailing slashes from a base URL', async () => {
    // Consumers append paths, so a trailing slash here would produce `//api/...`.
    respondWith({ someUrl: 'https://ps.example.com/' });

    expect(await getDeploymentBaseUrl('someUrl')).toBe('https://ps.example.com');
  });

  it('leaves a URL without a trailing slash untouched', async () => {
    respondWith({ someUrl: 'https://ps.example.com' });

    expect(await getDeploymentBaseUrl('someUrl')).toBe('https://ps.example.com');
  });

  it('resolves undefined for an absent asset, so callers use their own default', async () => {
    // The normal case for a web build with no Docker entrypoint.
    fetchSpy.and.returnValue(
      Promise.resolve({ ok: false, json: () => Promise.resolve({}) }),
    );

    expect(await getDeploymentString('plainspaceHost')).toBeUndefined();
  });

  it('handles the committed placeholder asset', async () => {
    // What every non-Docker deploy receives: the placeholder is committed to the
    // repo and served with HTTP 200, so `res.ok` passes and the JSON parses. Only
    // the absent key keeps the shipped default correct.
    respondWith({
      _comment:
        'This JSON file will be regenerated by docker-entrypoint.sh based on environment variables in docker environment.',
    });

    expect(await getDeploymentString('plainspaceHost')).toBeUndefined();
  });

  it('resolves undefined rather than throwing when the asset cannot be parsed', async () => {
    fetchSpy.and.returnValue(
      Promise.resolve({
        ok: true,
        json: () => Promise.reject(new SyntaxError('Unexpected token')),
      }),
    );

    expect(await getDeploymentString('plainspaceHost')).toBeUndefined();
  });

  it('tolerates a non-object body, such as an SPA fallback page', async () => {
    // nginx can serve index.html for a missing asset, so a 200 does not imply JSON.
    for (const body of ['<html></html>', [1, 2], null, 'text']) {
      resetDeploymentOverridesCache();
      respondWith(body);
      expect(await getDeploymentString('plainspaceHost')).toBeUndefined();
    }
  });

  it('fetches once and caches, so an absent asset is not re-requested', async () => {
    respondWith({});

    await getDeploymentString('someKey');
    await getDeploymentString('otherKey');
    await getDeploymentBaseUrl('someUrl');

    expect(fetchSpy).toHaveBeenCalledTimes(1);
  });

  it('caches a failed fetch too', async () => {
    fetchSpy.and.returnValue(
      Promise.resolve({ ok: false, json: () => Promise.resolve({}) }),
    );

    await getDeploymentString('someKey');
    await getDeploymentString('someKey');

    expect(fetchSpy).toHaveBeenCalledTimes(1);
  });
});
