import {
  resolveDefaultPlainspaceHost,
  resetDefaultPlainspaceHostCache,
} from './plainspace-default-host.util';
import { DEFAULT_PLAINSPACE_CFG } from './plainspace-cfg-form.const';

describe('resolveDefaultPlainspaceHost', () => {
  let fetchSpy: jasmine.Spy;

  const respondWith = (body: unknown): void => {
    fetchSpy.and.returnValue(
      Promise.resolve({ ok: true, json: () => Promise.resolve(body) }),
    );
  };

  beforeEach(() => {
    resetDefaultPlainspaceHostCache();
    fetchSpy = spyOn(window, 'fetch');
  });

  afterEach(() => {
    resetDefaultPlainspaceHostCache();
  });

  it('returns the host from the runtime override asset', async () => {
    // The mechanism docker-entrypoint.sh uses for PLAINSPACE_HOST. Build-time env
    // cannot be used here: env.generated.ts is compiled into the image, so a
    // variable set on a published image never reaches the running app.
    respondWith({ plainspaceHost: 'https://ps.example.com' });

    expect(await resolveDefaultPlainspaceHost()).toBe('https://ps.example.com');
    expect(fetchSpy).toHaveBeenCalledWith('assets/sync-config-default-override.json');
  });

  it('normalizes whitespace and trailing slashes so the stored host is a clean base URL', async () => {
    // The API service appends paths to this value, so a trailing slash here would
    // produce `//api/integration/...` in every request URL.
    respondWith({ plainspaceHost: '  https://ps.example.com/  ' });

    expect(await resolveDefaultPlainspaceHost()).toBe('https://ps.example.com');
  });

  it('resolves null when the asset is absent, so callers use their own default', async () => {
    // The normal case for a web build with no Docker entrypoint.
    fetchSpy.and.returnValue(
      Promise.resolve({ ok: false, json: () => Promise.resolve({}) }),
    );

    expect(await resolveDefaultPlainspaceHost()).toBeNull();
  });

  it('resolves null against the committed placeholder asset', async () => {
    // What every web deployment and an env-var-free Docker run actually receive:
    // the placeholder is committed to the repo and SERVED with HTTP 200 (nginx
    // returns it before the SPA fallback), so `res.ok` passes and the JSON parses.
    // Only the absent key keeps the hosted default correct here.
    respondWith({
      _comment:
        'This JSON file will be regenerated by docker-entrypoint.sh based on environment variables in docker environment.',
    });

    expect(await resolveDefaultPlainspaceHost()).toBeNull();
  });

  it('resolves null when the key is missing, empty, or not a string', async () => {
    // A malformed env var must not reach the API service as a host.
    for (const plainspaceHost of [undefined, null, '', '   ', 42, {}]) {
      resetDefaultPlainspaceHostCache();
      respondWith({ plainspaceHost });
      expect(await resolveDefaultPlainspaceHost()).toBeNull();
    }
  });

  it('resolves null rather than throwing when the asset cannot be parsed', async () => {
    fetchSpy.and.returnValue(
      Promise.resolve({
        ok: true,
        json: () => Promise.reject(new SyntaxError('Unexpected token')),
      }),
    );

    expect(await resolveDefaultPlainspaceHost()).toBeNull();
  });

  it('prefers the override over the compiled-in default', async () => {
    // Guards the actual point of the feature: a self-hosted instance must not
    // silently fall back to plainspace.org.
    expect(DEFAULT_PLAINSPACE_CFG.host).toBe('https://plainspace.org');

    respondWith({ plainspaceHost: 'https://ps.internal' });

    expect(await resolveDefaultPlainspaceHost()).toBe('https://ps.internal');
    expect(DEFAULT_PLAINSPACE_CFG.host).toBe('https://plainspace.org');
  });
});
